set_operating_conditions -process maximum
set_operating_conditions -process typical
set _xlnx_shared_i0 [all_outputs]
set_load 1.000 $_xlnx_shared_i0
set_operating_conditions -heatsink high
set_load 0.000 $_xlnx_shared_i0
set_property LOAD 0 [get_ports {HADDR[0]}]
set_property LOAD 0 [get_ports {HADDR[10]}]
set_property LOAD 0 [get_ports {HADDR[11]}]
set_property LOAD 0 [get_ports {HADDR[12]}]
set_property LOAD 0 [get_ports {HADDR[13]}]
set_property LOAD 0 [get_ports {HADDR[14]}]
set_property LOAD 0 [get_ports {HADDR[15]}]
set_property LOAD 0 [get_ports {HADDR[16]}]
set_property LOAD 0 [get_ports {HADDR[17]}]
set_property LOAD 0 [get_ports {HADDR[18]}]
set_property LOAD 0 [get_ports {HADDR[19]}]
set_property LOAD 0 [get_ports {HADDR[1]}]
set_property LOAD 0 [get_ports {HADDR[20]}]
set_property LOAD 0 [get_ports {HADDR[21]}]
set_property LOAD 0 [get_ports {HADDR[22]}]
set_property LOAD 0 [get_ports {HADDR[23]}]
set_property LOAD 0 [get_ports {HADDR[24]}]
set_property LOAD 0 [get_ports {HADDR[25]}]
set_property LOAD 0 [get_ports {HADDR[26]}]
set_property LOAD 0 [get_ports {HADDR[27]}]
set_property LOAD 0 [get_ports {HADDR[28]}]
set_property LOAD 0 [get_ports {HADDR[29]}]
set_property LOAD 0 [get_ports {HADDR[2]}]
set_property LOAD 0 [get_ports {HADDR[30]}]
set_property LOAD 0 [get_ports {HADDR[31]}]
set_property LOAD 0 [get_ports {HADDR[32]}]
set_property LOAD 0 [get_ports {HADDR[33]}]
set_property LOAD 0 [get_ports {HADDR[34]}]
set_property LOAD 0 [get_ports {HADDR[35]}]
set_property LOAD 0 [get_ports {HADDR[36]}]
set_property LOAD 0 [get_ports {HADDR[37]}]
set_property LOAD 0 [get_ports {HADDR[38]}]
set_property LOAD 0 [get_ports {HADDR[39]}]
set_property LOAD 0 [get_ports {HADDR[3]}]
set_property LOAD 0 [get_ports {HADDR[40]}]
set_property LOAD 0 [get_ports {HADDR[41]}]
set_property LOAD 0 [get_ports {HADDR[42]}]
set_property LOAD 0 [get_ports {HADDR[43]}]
set_property LOAD 0 [get_ports {HADDR[44]}]
set_property LOAD 0 [get_ports {HADDR[45]}]
set_property LOAD 0 [get_ports {HADDR[46]}]
set_property LOAD 0 [get_ports {HADDR[47]}]
set_property LOAD 0 [get_ports {HADDR[48]}]
set_property LOAD 0 [get_ports {HADDR[49]}]
set_property LOAD 0 [get_ports {HADDR[4]}]
set_property LOAD 0 [get_ports {HADDR[50]}]
set_property LOAD 0 [get_ports {HADDR[51]}]
set_property LOAD 0 [get_ports {HADDR[52]}]
set_property LOAD 0 [get_ports {HADDR[53]}]
set_property LOAD 0 [get_ports {HADDR[54]}]
set_property LOAD 0 [get_ports {HADDR[55]}]
set_property LOAD 0 [get_ports {HADDR[56]}]
set_property LOAD 0 [get_ports {HADDR[57]}]
set_property LOAD 0 [get_ports {HADDR[58]}]
set_property LOAD 0 [get_ports {HADDR[59]}]
set_property LOAD 0 [get_ports {HADDR[5]}]
set_property LOAD 0 [get_ports {HADDR[60]}]
set_property LOAD 0 [get_ports {HADDR[61]}]
set_property LOAD 0 [get_ports {HADDR[62]}]
set_property LOAD 0 [get_ports {HADDR[63]}]
set_property LOAD 0 [get_ports {HADDR[6]}]
set_property LOAD 0 [get_ports {HADDR[7]}]
set_property LOAD 0 [get_ports {HADDR[8]}]
set_property LOAD 0 [get_ports {HADDR[9]}]
set_property LOAD 0 [get_ports HREADY]
set_property LOAD 0 [get_ports {HSIZE[0]}]
set_property LOAD 0 [get_ports {HSIZE[1]}]
set_property LOAD 0 [get_ports {HSIZE[2]}]
set_property LOAD 0 [get_ports HWRITE_OUT]
set_property LOAD 0 [get_ports {addr_width[0]}]
set_property LOAD 0 [get_ports {addr_width[1]}]
set_property LOAD 0 [get_ports {encrypted_addr[0]}]
set_property LOAD 0 [get_ports {encrypted_addr[100]}]
set_property LOAD 0 [get_ports {encrypted_addr[101]}]
set_property LOAD 0 [get_ports {encrypted_addr[102]}]
set_property LOAD 0 [get_ports {encrypted_addr[103]}]
set_property LOAD 0 [get_ports {encrypted_addr[104]}]
set_property LOAD 0 [get_ports {encrypted_addr[105]}]
set_property LOAD 0 [get_ports {encrypted_addr[106]}]
set_property LOAD 0 [get_ports {encrypted_addr[107]}]
set_property LOAD 0 [get_ports {encrypted_addr[108]}]
set_property LOAD 0 [get_ports {encrypted_addr[109]}]
set_property LOAD 0 [get_ports {encrypted_addr[10]}]
set_property LOAD 0 [get_ports {encrypted_addr[110]}]
set_property LOAD 0 [get_ports {encrypted_addr[111]}]
set_property LOAD 0 [get_ports {encrypted_addr[112]}]
set_property LOAD 0 [get_ports {encrypted_addr[113]}]
set_property LOAD 0 [get_ports {encrypted_addr[114]}]
set_property LOAD 0 [get_ports {encrypted_addr[115]}]
set_property LOAD 0 [get_ports {encrypted_addr[116]}]
set_property LOAD 0 [get_ports {encrypted_addr[117]}]
set_property LOAD 0 [get_ports {encrypted_addr[118]}]
set_property LOAD 0 [get_ports {encrypted_addr[119]}]
set_property LOAD 0 [get_ports {encrypted_addr[11]}]
set_property LOAD 0 [get_ports {encrypted_addr[120]}]
set_property LOAD 0 [get_ports {encrypted_addr[121]}]
set_property LOAD 0 [get_ports {encrypted_addr[122]}]
set_property LOAD 0 [get_ports {encrypted_addr[123]}]
set_property LOAD 0 [get_ports {encrypted_addr[124]}]
set_property LOAD 0 [get_ports {encrypted_addr[125]}]
set_property LOAD 0 [get_ports {encrypted_addr[126]}]
set_property LOAD 0 [get_ports {encrypted_addr[127]}]
set_property LOAD 0 [get_ports {encrypted_addr[12]}]
set_property LOAD 0 [get_ports {encrypted_addr[13]}]
set_property LOAD 0 [get_ports {encrypted_addr[14]}]
set_property LOAD 0 [get_ports {encrypted_addr[15]}]
set_property LOAD 0 [get_ports {encrypted_addr[16]}]
set_property LOAD 0 [get_ports {encrypted_addr[17]}]
set_property LOAD 0 [get_ports {encrypted_addr[18]}]
set_property LOAD 0 [get_ports {encrypted_addr[19]}]
set_property LOAD 0 [get_ports {encrypted_addr[1]}]
set_property LOAD 0 [get_ports {encrypted_addr[20]}]
set_property LOAD 0 [get_ports {encrypted_addr[21]}]
set_property LOAD 0 [get_ports {encrypted_addr[22]}]
set_property LOAD 0 [get_ports {encrypted_addr[23]}]
set_property LOAD 0 [get_ports {encrypted_addr[24]}]
set_property LOAD 0 [get_ports {encrypted_addr[25]}]
set_property LOAD 0 [get_ports {encrypted_addr[26]}]
set_property LOAD 0 [get_ports {encrypted_addr[27]}]
set_property LOAD 0 [get_ports {encrypted_addr[28]}]
set_property LOAD 0 [get_ports {encrypted_addr[29]}]
set_property LOAD 0 [get_ports {encrypted_addr[2]}]
set_property LOAD 0 [get_ports {encrypted_addr[30]}]
set_property LOAD 0 [get_ports {encrypted_addr[31]}]
set_property LOAD 0 [get_ports {encrypted_addr[32]}]
set_property LOAD 0 [get_ports {encrypted_addr[33]}]
set_property LOAD 0 [get_ports {encrypted_addr[34]}]
set_property LOAD 0 [get_ports {encrypted_addr[35]}]
set_property LOAD 0 [get_ports {encrypted_addr[36]}]
set_property LOAD 0 [get_ports {encrypted_addr[37]}]
set_property LOAD 0 [get_ports {encrypted_addr[38]}]
set_property LOAD 0 [get_ports {encrypted_addr[39]}]
set_property LOAD 0 [get_ports {encrypted_addr[3]}]
set_property LOAD 0 [get_ports {encrypted_addr[40]}]
set_property LOAD 0 [get_ports {encrypted_addr[41]}]
set_property LOAD 0 [get_ports {encrypted_addr[42]}]
set_property LOAD 0 [get_ports {encrypted_addr[43]}]
set_property LOAD 0 [get_ports {encrypted_addr[44]}]
set_property LOAD 0 [get_ports {encrypted_addr[45]}]
set_property LOAD 0 [get_ports {encrypted_addr[46]}]
set_property LOAD 0 [get_ports {encrypted_addr[47]}]
set_property LOAD 0 [get_ports {encrypted_addr[48]}]
set_property LOAD 0 [get_ports {encrypted_addr[49]}]
set_property LOAD 0 [get_ports {encrypted_addr[4]}]
set_property LOAD 0 [get_ports {encrypted_addr[50]}]
set_property LOAD 0 [get_ports {encrypted_addr[51]}]
set_property LOAD 0 [get_ports {encrypted_addr[52]}]
set_property LOAD 0 [get_ports {encrypted_addr[53]}]
set_property LOAD 0 [get_ports {encrypted_addr[54]}]
set_property LOAD 0 [get_ports {encrypted_addr[55]}]
set_property LOAD 0 [get_ports {encrypted_addr[56]}]
set_property LOAD 0 [get_ports {encrypted_addr[57]}]
set_property LOAD 0 [get_ports {encrypted_addr[58]}]
set_property LOAD 0 [get_ports {encrypted_addr[59]}]
set_property LOAD 0 [get_ports {encrypted_addr[5]}]
set_property LOAD 0 [get_ports {encrypted_addr[60]}]
set_property LOAD 0 [get_ports {encrypted_addr[61]}]
set_property LOAD 0 [get_ports {encrypted_addr[62]}]
set_property LOAD 0 [get_ports {encrypted_addr[63]}]
set_property LOAD 0 [get_ports {encrypted_addr[64]}]
set_property LOAD 0 [get_ports {encrypted_addr[65]}]
set_property LOAD 0 [get_ports {encrypted_addr[66]}]
set_property LOAD 0 [get_ports {encrypted_addr[67]}]
set_property LOAD 0 [get_ports {encrypted_addr[68]}]
set_property LOAD 0 [get_ports {encrypted_addr[69]}]
set_property LOAD 0 [get_ports {encrypted_addr[6]}]
set_property LOAD 0 [get_ports {encrypted_addr[70]}]
set_property LOAD 0 [get_ports {encrypted_addr[71]}]
set_property LOAD 0 [get_ports {encrypted_addr[72]}]
set_property LOAD 0 [get_ports {encrypted_addr[73]}]
set_property LOAD 0 [get_ports {encrypted_addr[74]}]
set_property LOAD 0 [get_ports {encrypted_addr[75]}]
set_property LOAD 0 [get_ports {encrypted_addr[76]}]
set_property LOAD 0 [get_ports {encrypted_addr[77]}]
set_property LOAD 0 [get_ports {encrypted_addr[78]}]
set_property LOAD 0 [get_ports {encrypted_addr[79]}]
set_property LOAD 0 [get_ports {encrypted_addr[7]}]
set_property LOAD 0 [get_ports {encrypted_addr[80]}]
set_property LOAD 0 [get_ports {encrypted_addr[81]}]
set_property LOAD 0 [get_ports {encrypted_addr[82]}]
set_property LOAD 0 [get_ports {encrypted_addr[83]}]
set_property LOAD 0 [get_ports {encrypted_addr[84]}]
set_property LOAD 0 [get_ports {encrypted_addr[85]}]
set_property LOAD 0 [get_ports {encrypted_addr[86]}]
set_property LOAD 0 [get_ports {encrypted_addr[87]}]
set_property LOAD 0 [get_ports {encrypted_addr[88]}]
set_property LOAD 0 [get_ports {encrypted_addr[89]}]
set_property LOAD 0 [get_ports {encrypted_addr[8]}]
set_property LOAD 0 [get_ports {encrypted_addr[90]}]
set_property LOAD 0 [get_ports {encrypted_addr[91]}]
set_property LOAD 0 [get_ports {encrypted_addr[92]}]
set_property LOAD 0 [get_ports {encrypted_addr[93]}]
set_property LOAD 0 [get_ports {encrypted_addr[94]}]
set_property LOAD 0 [get_ports {encrypted_addr[95]}]
set_property LOAD 0 [get_ports {encrypted_addr[96]}]
set_property LOAD 0 [get_ports {encrypted_addr[97]}]
set_property LOAD 0 [get_ports {encrypted_addr[98]}]
set_property LOAD 0 [get_ports {encrypted_addr[99]}]
set_property LOAD 0 [get_ports {encrypted_addr[9]}]
set_operating_conditions -ambient_temp 30.0
set_operating_conditions -airflow 500
set_operating_conditions -design_power_budget 2.0
set_operating_conditions -voltage {vccint 0.990}
set_operating_conditions -voltage {vccaux 1.710}
set_operating_conditions -voltage {vcco33 1.140}
set_operating_conditions -voltage {vcco25 2.380}
set_operating_conditions -voltage {vcco18 1.140}
set_operating_conditions -voltage {vcco15 1.430}
set_operating_conditions -voltage {vcco135 1.300}
set_operating_conditions -voltage {vcco12 1.140}
set_operating_conditions -voltage {vccaux_io 1.710}
set_operating_conditions -voltage {vccbram 0.970}
set_operating_conditions -voltage {mgtavcc 0.970}
set_operating_conditions -voltage {mgtavtt 1.170}
set_operating_conditions -voltage {mgtvccaux 1.750}
set_operating_conditions -voltage {vccadc 1.750}
